# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ravi/Downloads/project-2025 10 2220 42 01"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ravi/Downloads/project-2025 10 2220 42 01"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ravi/Downloads/project-2025 10 2220 42 01/CMakeFiles" "/home/ravi/Downloads/project-2025 10 2220 42 01//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ravi/Downloads/project-2025 10 2220 42 01/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dnn

# Build rule for target.
dnn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dnn
.PHONY : dnn

# fast build rule for target.
dnn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/build
.PHONY : dnn/fast

#=============================================================================
# Target rules for targets named dnn_static

# Build rule for target.
dnn_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dnn_static
.PHONY : dnn_static

# fast build rule for target.
dnn_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/build
.PHONY : dnn_static/fast

#=============================================================================
# Target rules for targets named test_tensor_system

# Build rule for target.
test_tensor_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tensor_system
.PHONY : test_tensor_system

# fast build rule for target.
test_tensor_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_system.dir/build.make CMakeFiles/test_tensor_system.dir/build
.PHONY : test_tensor_system/fast

#=============================================================================
# Target rules for targets named test_tensor_only

# Build rule for target.
test_tensor_only: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tensor_only
.PHONY : test_tensor_only

# fast build rule for target.
test_tensor_only/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_only.dir/build.make CMakeFiles/test_tensor_only.dir/build
.PHONY : test_tensor_only/fast

#=============================================================================
# Target rules for targets named test_tensor_simple

# Build rule for target.
test_tensor_simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tensor_simple
.PHONY : test_tensor_simple

# fast build rule for target.
test_tensor_simple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_simple.dir/build.make CMakeFiles/test_tensor_simple.dir/build
.PHONY : test_tensor_simple/fast

#=============================================================================
# Target rules for targets named test_tensor

# Build rule for target.
test_tensor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tensor
.PHONY : test_tensor

# fast build rule for target.
test_tensor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor.dir/build.make CMakeFiles/test_tensor.dir/build
.PHONY : test_tensor/fast

#=============================================================================
# Target rules for targets named xor_example

# Build rule for target.
xor_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xor_example
.PHONY : xor_example

# fast build rule for target.
xor_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xor_example.dir/build.make CMakeFiles/xor_example.dir/build
.PHONY : xor_example/fast

#=============================================================================
# Target rules for targets named mnist_example

# Build rule for target.
mnist_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mnist_example
.PHONY : mnist_example

# fast build rule for target.
mnist_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_example.dir/build.make CMakeFiles/mnist_example.dir/build
.PHONY : mnist_example/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test_optimizers

# Build rule for target.
test_optimizers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_optimizers
.PHONY : test_optimizers

# fast build rule for target.
test_optimizers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_optimizers.dir/build.make CMakeFiles/test_optimizers.dir/build
.PHONY : test_optimizers/fast

apps/main.o: apps/main.cpp.o
.PHONY : apps/main.o

# target to build an object file
apps/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/apps/main.cpp.o
.PHONY : apps/main.cpp.o

apps/main.i: apps/main.cpp.i
.PHONY : apps/main.i

# target to preprocess a source file
apps/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/apps/main.cpp.i
.PHONY : apps/main.cpp.i

apps/main.s: apps/main.cpp.s
.PHONY : apps/main.s

# target to generate assembly for a file
apps/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/apps/main.cpp.s
.PHONY : apps/main.cpp.s

examples/mnist_example.o: examples/mnist_example.cpp.o
.PHONY : examples/mnist_example.o

# target to build an object file
examples/mnist_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_example.dir/build.make CMakeFiles/mnist_example.dir/examples/mnist_example.cpp.o
.PHONY : examples/mnist_example.cpp.o

examples/mnist_example.i: examples/mnist_example.cpp.i
.PHONY : examples/mnist_example.i

# target to preprocess a source file
examples/mnist_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_example.dir/build.make CMakeFiles/mnist_example.dir/examples/mnist_example.cpp.i
.PHONY : examples/mnist_example.cpp.i

examples/mnist_example.s: examples/mnist_example.cpp.s
.PHONY : examples/mnist_example.s

# target to generate assembly for a file
examples/mnist_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_example.dir/build.make CMakeFiles/mnist_example.dir/examples/mnist_example.cpp.s
.PHONY : examples/mnist_example.cpp.s

examples/xor_example.o: examples/xor_example.cpp.o
.PHONY : examples/xor_example.o

# target to build an object file
examples/xor_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xor_example.dir/build.make CMakeFiles/xor_example.dir/examples/xor_example.cpp.o
.PHONY : examples/xor_example.cpp.o

examples/xor_example.i: examples/xor_example.cpp.i
.PHONY : examples/xor_example.i

# target to preprocess a source file
examples/xor_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xor_example.dir/build.make CMakeFiles/xor_example.dir/examples/xor_example.cpp.i
.PHONY : examples/xor_example.cpp.i

examples/xor_example.s: examples/xor_example.cpp.s
.PHONY : examples/xor_example.s

# target to generate assembly for a file
examples/xor_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xor_example.dir/build.make CMakeFiles/xor_example.dir/examples/xor_example.cpp.s
.PHONY : examples/xor_example.cpp.s

src/dnn.o: src/dnn.cpp.o
.PHONY : src/dnn.o

# target to build an object file
src/dnn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/dnn.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/dnn.cpp.o
.PHONY : src/dnn.cpp.o

src/dnn.i: src/dnn.cpp.i
.PHONY : src/dnn.i

# target to preprocess a source file
src/dnn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/dnn.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/dnn.cpp.i
.PHONY : src/dnn.cpp.i

src/dnn.s: src/dnn.cpp.s
.PHONY : src/dnn.s

# target to generate assembly for a file
src/dnn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/dnn.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/dnn.cpp.s
.PHONY : src/dnn.cpp.s

src/layers.o: src/layers.cpp.o
.PHONY : src/layers.o

# target to build an object file
src/layers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/layers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/layers.cpp.o
.PHONY : src/layers.cpp.o

src/layers.i: src/layers.cpp.i
.PHONY : src/layers.i

# target to preprocess a source file
src/layers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/layers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/layers.cpp.i
.PHONY : src/layers.cpp.i

src/layers.s: src/layers.cpp.s
.PHONY : src/layers.s

# target to generate assembly for a file
src/layers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/layers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/layers.cpp.s
.PHONY : src/layers.cpp.s

src/optimizers.o: src/optimizers.cpp.o
.PHONY : src/optimizers.o

# target to build an object file
src/optimizers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/optimizers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/optimizers.cpp.o
.PHONY : src/optimizers.cpp.o

src/optimizers.i: src/optimizers.cpp.i
.PHONY : src/optimizers.i

# target to preprocess a source file
src/optimizers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/optimizers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/optimizers.cpp.i
.PHONY : src/optimizers.cpp.i

src/optimizers.s: src/optimizers.cpp.s
.PHONY : src/optimizers.s

# target to generate assembly for a file
src/optimizers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/optimizers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/optimizers.cpp.s
.PHONY : src/optimizers.cpp.s

src/tensor.o: src/tensor.cpp.o
.PHONY : src/tensor.o

# target to build an object file
src/tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/tensor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/tensor.cpp.o
.PHONY : src/tensor.cpp.o

src/tensor.i: src/tensor.cpp.i
.PHONY : src/tensor.i

# target to preprocess a source file
src/tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/tensor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/tensor.cpp.i
.PHONY : src/tensor.cpp.i

src/tensor.s: src/tensor.cpp.s
.PHONY : src/tensor.s

# target to generate assembly for a file
src/tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn.dir/build.make CMakeFiles/dnn.dir/src/tensor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dnn_static.dir/build.make CMakeFiles/dnn_static.dir/src/tensor.cpp.s
.PHONY : src/tensor.cpp.s

test_optimizers.o: test_optimizers.cpp.o
.PHONY : test_optimizers.o

# target to build an object file
test_optimizers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_optimizers.dir/build.make CMakeFiles/test_optimizers.dir/test_optimizers.cpp.o
.PHONY : test_optimizers.cpp.o

test_optimizers.i: test_optimizers.cpp.i
.PHONY : test_optimizers.i

# target to preprocess a source file
test_optimizers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_optimizers.dir/build.make CMakeFiles/test_optimizers.dir/test_optimizers.cpp.i
.PHONY : test_optimizers.cpp.i

test_optimizers.s: test_optimizers.cpp.s
.PHONY : test_optimizers.s

# target to generate assembly for a file
test_optimizers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_optimizers.dir/build.make CMakeFiles/test_optimizers.dir/test_optimizers.cpp.s
.PHONY : test_optimizers.cpp.s

test_tensor.o: test_tensor.cpp.o
.PHONY : test_tensor.o

# target to build an object file
test_tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor.dir/build.make CMakeFiles/test_tensor.dir/test_tensor.cpp.o
.PHONY : test_tensor.cpp.o

test_tensor.i: test_tensor.cpp.i
.PHONY : test_tensor.i

# target to preprocess a source file
test_tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor.dir/build.make CMakeFiles/test_tensor.dir/test_tensor.cpp.i
.PHONY : test_tensor.cpp.i

test_tensor.s: test_tensor.cpp.s
.PHONY : test_tensor.s

# target to generate assembly for a file
test_tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor.dir/build.make CMakeFiles/test_tensor.dir/test_tensor.cpp.s
.PHONY : test_tensor.cpp.s

test_tensor_only.o: test_tensor_only.cpp.o
.PHONY : test_tensor_only.o

# target to build an object file
test_tensor_only.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_only.dir/build.make CMakeFiles/test_tensor_only.dir/test_tensor_only.cpp.o
.PHONY : test_tensor_only.cpp.o

test_tensor_only.i: test_tensor_only.cpp.i
.PHONY : test_tensor_only.i

# target to preprocess a source file
test_tensor_only.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_only.dir/build.make CMakeFiles/test_tensor_only.dir/test_tensor_only.cpp.i
.PHONY : test_tensor_only.cpp.i

test_tensor_only.s: test_tensor_only.cpp.s
.PHONY : test_tensor_only.s

# target to generate assembly for a file
test_tensor_only.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_only.dir/build.make CMakeFiles/test_tensor_only.dir/test_tensor_only.cpp.s
.PHONY : test_tensor_only.cpp.s

test_tensor_simple.o: test_tensor_simple.cpp.o
.PHONY : test_tensor_simple.o

# target to build an object file
test_tensor_simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_simple.dir/build.make CMakeFiles/test_tensor_simple.dir/test_tensor_simple.cpp.o
.PHONY : test_tensor_simple.cpp.o

test_tensor_simple.i: test_tensor_simple.cpp.i
.PHONY : test_tensor_simple.i

# target to preprocess a source file
test_tensor_simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_simple.dir/build.make CMakeFiles/test_tensor_simple.dir/test_tensor_simple.cpp.i
.PHONY : test_tensor_simple.cpp.i

test_tensor_simple.s: test_tensor_simple.cpp.s
.PHONY : test_tensor_simple.s

# target to generate assembly for a file
test_tensor_simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_simple.dir/build.make CMakeFiles/test_tensor_simple.dir/test_tensor_simple.cpp.s
.PHONY : test_tensor_simple.cpp.s

test_tensor_system.o: test_tensor_system.cpp.o
.PHONY : test_tensor_system.o

# target to build an object file
test_tensor_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_system.dir/build.make CMakeFiles/test_tensor_system.dir/test_tensor_system.cpp.o
.PHONY : test_tensor_system.cpp.o

test_tensor_system.i: test_tensor_system.cpp.i
.PHONY : test_tensor_system.i

# target to preprocess a source file
test_tensor_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_system.dir/build.make CMakeFiles/test_tensor_system.dir/test_tensor_system.cpp.i
.PHONY : test_tensor_system.cpp.i

test_tensor_system.s: test_tensor_system.cpp.s
.PHONY : test_tensor_system.s

# target to generate assembly for a file
test_tensor_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_system.dir/build.make CMakeFiles/test_tensor_system.dir/test_tensor_system.cpp.s
.PHONY : test_tensor_system.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... dnn"
	@echo "... dnn_static"
	@echo "... main"
	@echo "... mnist_example"
	@echo "... test_optimizers"
	@echo "... test_tensor"
	@echo "... test_tensor_only"
	@echo "... test_tensor_simple"
	@echo "... test_tensor_system"
	@echo "... xor_example"
	@echo "... apps/main.o"
	@echo "... apps/main.i"
	@echo "... apps/main.s"
	@echo "... examples/mnist_example.o"
	@echo "... examples/mnist_example.i"
	@echo "... examples/mnist_example.s"
	@echo "... examples/xor_example.o"
	@echo "... examples/xor_example.i"
	@echo "... examples/xor_example.s"
	@echo "... src/dnn.o"
	@echo "... src/dnn.i"
	@echo "... src/dnn.s"
	@echo "... src/layers.o"
	@echo "... src/layers.i"
	@echo "... src/layers.s"
	@echo "... src/optimizers.o"
	@echo "... src/optimizers.i"
	@echo "... src/optimizers.s"
	@echo "... src/tensor.o"
	@echo "... src/tensor.i"
	@echo "... src/tensor.s"
	@echo "... test_optimizers.o"
	@echo "... test_optimizers.i"
	@echo "... test_optimizers.s"
	@echo "... test_tensor.o"
	@echo "... test_tensor.i"
	@echo "... test_tensor.s"
	@echo "... test_tensor_only.o"
	@echo "... test_tensor_only.i"
	@echo "... test_tensor_only.s"
	@echo "... test_tensor_simple.o"
	@echo "... test_tensor_simple.i"
	@echo "... test_tensor_simple.s"
	@echo "... test_tensor_system.o"
	@echo "... test_tensor_system.i"
	@echo "... test_tensor_system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

